// Generated by CoffeeScript 1.6.3
(function() {
  var Game, handleMessage;

  Game = {
    id: 1,
    divId: 'game',
    url: 'http://176.37.65.38/',
    subfield: 0,
    socket: null,
    create: function() {
      var boardHtml, i, j, k, m, rowHtml, _i, _j, _k, _l;
      boardHtml = '<table class="game_board" cellspacing="0" cellpadding="0">';
      boardHtml += '<tbody>';
      for (i = _i = 1; _i <= 3; i = ++_i) {
        rowHtml = '<tr>';
        for (j = _j = 1; _j <= 3; j = ++_j) {
          rowHtml += '<td align="center">';
          rowHtml += '<table class="inner_board" cellspacing="0" cellpadding="0">';
          rowHtml += '<tbody>';
          for (k = _k = 1; _k <= 3; k = ++_k) {
            rowHtml += '<tr>';
            for (m = _l = 1; _l <= 3; m = ++_l) {
              rowHtml += '<td align="center"></td>';
            }
            rowHtml += '</tr>';
          }
          rowHtml += '</tbody>';
          rowHtml += '</table>';
          rowHtml += '</td>';
        }
        rowHtml += '</tr>';
        boardHtml += rowHtml;
      }
      boardHtml += '</tbody>';
      boardHtml += '</table>';
      return $('#' + this.divId).html(boardHtml);
    },
    connect: function(url) {
      this.url = url;
      this.socket = new SockJS(this.url);
      this.socket.onopen = function() {
        return console.log("socket opened");
      };
      this.socket.onclose = function() {
        return console.log("socket closed");
      };
      return this.socket.onmessage = function(message) {
        return handleMessage(message);
      };
    },
    start: function() {
      return alert("not implemented yet");
    },
    connectionDropped: function() {
      return alert("not implemented yet");
    },
    end: function() {
      return alert("not implemented yet");
    },
    move: function() {
      return alert("not implemented yet");
    }
  };

  handleMessage = function(message) {
    return console.log("message");
  };

  window.initGame = function(divId) {
    this.game = $.extend(true, {}, Game);
    this.game.divId = divId;
    this.game.create();
    return this.game.connect("http://localhost:3000/socks_api");
  };

  window.changeName = function() {
    return alert("not implemented yet");
  };

  window.showRules = function() {
    return new Messi('testtesttest', {
      title: 'Rules',
      modal: true
    });
  };

}).call(this);
