// Generated by CoffeeScript 1.6.3
(function() {
  var Game;

  Game = {
    id: 1,
    divId: 'game',
    url: 'http://176.37.65.38/',
    websocketPort: 1337,
    subfield: 0,
    create: function() {
      var boardHtml, i, j, k, m, rowHtml, _i, _j, _k, _l;
      boardHtml = '<table class="game_board" cellspacing="0" cellpadding="0">';
      boardHtml += '<tbody>';
      for (i = _i = 1; _i <= 3; i = ++_i) {
        rowHtml = '<tr>';
        for (j = _j = 1; _j <= 3; j = ++_j) {
          rowHtml += '<td align="center">';
          rowHtml += '<table class="inner_board" cellspacing="0" cellpadding="0">';
          rowHtml += '<tbody>';
          for (k = _k = 1; _k <= 3; k = ++_k) {
            rowHtml += '<tr>';
            for (m = _l = 1; _l <= 3; m = ++_l) {
              rowHtml += '<td align="center"></td>';
            }
            rowHtml += '</tr>';
          }
          rowHtml += '</tbody>';
          rowHtml += '</table>';
          rowHtml += '</td>';
        }
        rowHtml += '<tr>';
        boardHtml += rowHtml;
      }
      boardHtml += '</tbody>';
      boardHtml += '</table>';
      return $('#' + this.divId).html(boardHtml);
    },
    connect: function(url, port) {
      return alert("not implemented yet");
    },
    start: function() {
      return alert("not implemented yet");
    },
    connectionDropped: function() {
      return alert("not implemented yet");
    },
    end: function() {
      return alert("not implemented yet");
    },
    move: function() {
      return alert("not implemented yet");
    }
  };

  window.initGame = function(divId) {
    var game;
    game = $.extend(true, {}, Game);
    game.divId = divId;
    return game.create();
  };

}).call(this);
